# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"\x15\n\x06GetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\"*\n\x08GetReply\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x66ined\x18\x02 \x01(\x08\"7\n\x06SetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tbroadcast\x18\x03 \x01(\x08\"\x19\n\x08SetReply\x12\r\n\x05value\x18\x01 \x01(\t\"\x06\n\x04Void\"\x10\n\x02IP\x12\n\n\x02ip\x18\x01 \x01(\t\"d\n\nStoreReply\x12(\n\x05store\x18\x01 \x03(\x0b\x32\x19.kv.StoreReply.StoreEntry\x1a,\n\nStoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa0\x01\n\x06\x43lient\x12!\n\x03Get\x12\n.kv.GetKey\x1a\x0c.kv.GetReply\"\x00\x12!\n\x03Set\x12\n.kv.SetKey\x1a\x0c.kv.SetReply\"\x00\x12\"\n\x04List\x12\x08.kv.Void\x1a\x0e.kv.StoreReply\"\x00\x12,\n\x10RegisterWithPeer\x12\x06.kv.IP\x1a\x0e.kv.StoreReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOREREPLY_STOREENTRY._options = None
  _STOREREPLY_STOREENTRY._serialized_options = b'8\001'
  _globals['_GETKEY']._serialized_start=16
  _globals['_GETKEY']._serialized_end=37
  _globals['_GETREPLY']._serialized_start=39
  _globals['_GETREPLY']._serialized_end=81
  _globals['_SETKEY']._serialized_start=83
  _globals['_SETKEY']._serialized_end=138
  _globals['_SETREPLY']._serialized_start=140
  _globals['_SETREPLY']._serialized_end=165
  _globals['_VOID']._serialized_start=167
  _globals['_VOID']._serialized_end=173
  _globals['_IP']._serialized_start=175
  _globals['_IP']._serialized_end=191
  _globals['_STOREREPLY']._serialized_start=193
  _globals['_STOREREPLY']._serialized_end=293
  _globals['_STOREREPLY_STOREENTRY']._serialized_start=249
  _globals['_STOREREPLY_STOREENTRY']._serialized_end=293
  _globals['_CLIENT']._serialized_start=296
  _globals['_CLIENT']._serialized_end=456
# @@protoc_insertion_point(module_scope)
